language: python
python:
    - "2.7"
# command to install dependencies
install:
    - pip install pytest pytest-cov
    - pip install coveralls
    - pip install radon
    - pip install pep8
    - pip install mockito
# command to run tests
script:
    - py.test --cov . --cov-report term-missing
after_success:
    - radon cc ./src , ./tests
    - radon raw ./src , ./tests
    - radon mi ./src , ./tests
    - pep8 --statistics --count ./src
    - pep8 --statistics --count ./tests
    - coveralls
notifications:
    email:
        recipients:
            - danielardilayala@gmail.com
        on_failure: always